### ISSUE TITLE
[ISSUE] ErrorResponse 제안

### ISSUE THREAD

**Issue by mungmnb777** [tteokguk-please/tteokguk-api#12]
## Describe your changes
- 현재 ErrorResponse의 응답 데이터는 다음과 같은 포맷입니다.
```json
{
    "timeStamp": "2024-01-20T00:11:03.679024800",
    "errorCode": "Length",
    "errorMessage": "닉네임을 2 ~ 6글자로 입력해주세요."
}
```
- 다른 예외의 경우 해당 포맷으로 커버가 가능하지만, 파라미터 검증의 경우 어려움이 있습니다. 
- 따라서 다음과 같은 포맷을 제안합니다.
```json
{
    "timeStamp": "2024-01-20T00:11:03.679024800",
    "errorCode": "G002",
    "errorMessage": "파라미터 오류입니다.",
    "details": {
        "email": "이메일 형식을 지켜주세요.",
        "password":"영문, 숫자, 특수문자가 반드시 조합되어야 합니다.",
        "nickname":"닉네임을 2 ~ 6글자로 입력해주세요."
    }
}
```
- 기존 예외는 details에 null로 두고 사용하면 될 것 같습니다.

@h-beeen 

감사합니다.

**Comment by h-beeen** [comment]
동의합니다! details가 에러에 대해 더욱 자세한 정보를 담아 클라이언트가 활용하기 적합할 거라 예상이 됩니다!

**Comment by mungmnb777** [comment]
> 동의합니다! details가 에러에 대해 더욱 자세한 정보를 담아 클라이언트가 활용하기 적합할 거라 예상이 됩니다!

넵 그러면 제가 추가하겠습니다

**Comment by mungmnb777** [comment]
완료했습니다.
