### ISSUE TITLE
[INHANCE] userDetails.getUsername의 반환값이 StringType인 문제

### ISSUE THREAD

**Issue by h-beeen** [tteokguk-please/tteokguk-api#34]
## Related PR & Issue Ticket Number
- #32 

## Describe your changes
```java
        Member member = memberRepository.findById(Long.parseLong(user.getUsername()))
                .orElseThrow(() -> BusinessException.of(MEMBER_NOT_FOUND));
```

실제 코드레벨에서 활용할 때, Long으로 다시 파싱하여 사용하는 이슈가 있습니다.

## Next Step Todo
-

**Comment by mungmnb777** [comment]
이 문제는 인지하고 있습니다!

어제는 너무 피곤해서 해결법이 잘 안 떠올라서 못 고쳤는데,, 오늘 다시 해보겠습니다! 이 부분 최대한 빨리 고친 후에 알려드릴게요

**Comment by mungmnb777** [comment]
수정했습니다! #37
